== Ranging and synchronization

`*org.arl.unet.Services.RANGING*`

It is common to use underwater acoustic modems for range estimation, as the travel time of acoustic signals can easily be measured. In <<Propagation delay & ranging>>, we saw that we can use the `range` command to estimate range between nodes. This command uses the RANGING service described below.

Ranging is closely related to time synchronization, since travel time measurement between two nodes requires some sort of synchronization between the nodes. If the nodes are synchronized, one-way travel time (OWTT) can be directly measured and used to estimate range. If the nodes are not synchronized, two-way travel time (TWTT) can be used to measure range and synchronize the nodes simultaneously. The RANGING service supports both modes of ranging, and manages synchronization information between nodes.

The RANGING service also supports ranging to commercial-off-the-shelf (COTS) transponders.

=== Overview

The RANGING service provides messages and parameters to support OWTT and TWTT ranging to other Unet nodes or COTS transponders, and to manage synchronization information between the nodes.

==== Messages

The following messages are defined by the RANGING service:

* {url-unet-javadoc}org/arl/unet/localization/RangeReq.html[`RangeReq`^] => `AGREE` / `REFUSE` / `FAILURE` -- measure range to peer node via OWTT or TWTT
* {url-unet-javadoc}org/arl/unet/localization/BeaconReq.html[`BeaconReq`^] => `AGREE` / `REFUSE` / `FAILURE` -- transmit beacon message for OWTT
* {url-unet-javadoc}org/arl/unet/localization/RangeNtf.html[`RangeNtf`^] -- sent when a range to another node is measured, typically in response to `RangeReq` on current node (sent to requester), or `BeaconReq` on peer node (sent to agent's topic)
* {url-unet-javadoc}org/arl/unet/localization/InterrogationNtf.html[`InterrogationNtf`^] -- sent on agent's topic when a ranging interrogration frame is recevied from peer, before a response is sent back
* {url-unet-javadoc}org/arl/unet/localization/RespondReq.html[`RespondReq`^] => `AGREE` / `REFUSE` -- if automatic response is disabled, request to respond to interrogation frame (with optional payload)

The use of these messages will become clearer through examples below.

==== Parameters

The RANGING service does not define any parameters, but the default RANGING agent provides several useful parameters to control its behavior, and to provide status information.

=== Ranging agent

==== Parameters

A few parameters control the behavior of the default ranging agent:

* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#phy[`phy`^] -- physical agent to use for ranging
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#mac[`mac`^] -- MAC agent to use for channel reservations
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#respond[`respond`^] -- true if the agent should automatically respond to interrogation frames from peers, false if it should generate a `InterrogationNtf` and wait for another agent to request a response using `RespondReq`

In addition, the following parameters provide defaults for ranging:

* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#channel[`channel`^] -- channel (DATA/CONTROL) to use for ranging
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#maxRange[`maxRange`^] -- maximum expected range to peer (m)
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#ipreamble[`ipreamble`^] -- interrogation preamble to transmit
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#rpreamble[`rpreamble`^] -- response preamble to expect after interrogation
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#rsignal[`rsignal`^] -- response baseband signal to expect after interrogation
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#rdelay[`rdelay`^] -- response delay (seconds)
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#threshold[`threshold`^] -- threshold (0-1) for signal detection, when response is specified as an arbitrary acoustic signal

==== Indexed parameters

Some parameters can be additionally specified (or overridden) on a per-link basis, using indexed parameters (indexed by the node address of the peer node on the link):

* {url-unet-javadoc}org/arl/unet/localization/RangingNodeParam.html#address[`address`^] -- peer node address
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#channel[`channel`^] -- channel (DATA/CONTROL) to use for ranging
* {url-unet-javadoc}org/arl/unet/localization/RangingNodeParam.html#maxRange[`maxRange`^] -- maximum expected range to peer (m)
* {url-unet-javadoc}org/arl/unet/localization/RangingNodeParam.html#ipreamble[`ipreamble`^] -- interrogation preamble to transmit
* {url-unet-javadoc}org/arl/unet/localization/RangingNodeParam.html#isignal[`isignal`^] -- interrogation baseband signal to transmit
* {url-unet-javadoc}org/arl/unet/localization/RangingNodeParam.html#rpreamble[`rpreamble`^] -- response preamble to expect after interrogation
* {url-unet-javadoc}org/arl/unet/localization/RangingNodeParam.html#rsignal[`rsignal`^] -- response baseband signal to expect after interrogation
* {url-unet-javadoc}org/arl/unet/localization/RangingNodeParam.html#rdelay[`rdelay`^] -- response delay (seconds)
* {url-unet-javadoc}org/arl/unet/localization/RangingNodeParam.html#data[`data`^] -- payload data to automatically include in response frame
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#threshold[`threshold`^] -- threshold (0-1) for signal detection, when response is specified as an arbitrary acoustic signal
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#lifetime[`lifetime`^] -- synchronization validity lifetime (seconds)

The _lifetime_ of syncrhonization information should be set based on the expected drift of modem clocks. Lifetime is defined as the time for the expected clock drift (scaled by speed of sound in water) to exceed the required range estimation accuracy. If a network uses modems with low-drift clocks (such as oven-controlled oscillators), the lifetime can be quite long (hours to days). Without low-drift clocks, reasonable lifetimes may only be in the order of several minutes to tens of minutes.

.Why do clocks drift?
****
Most electronics use crystal oscillators for timekeeping. A crystal oscillator is an electronic circuit that uses the mechanical resonance of a vibrating piezoelectric crystal to create an electrical signal with a desired frequency. The resonant frequency depends on size, shape, elasticity, and the speed of sound in the material. Due to manufacturing tolerences, these properties are not exactly identical across manufactured crystals, and so different crystals designed for the same nominal frequency produce slightly different frequency signals. Furthermore, as the operating temperature of the crystal changes, its material properties change, and so does its resonant frequency. These differences in frequency are tiny, but over long periods of time, the differences accumulate and cause the clocks to drift.

For applications where drift is undesirable, temperature-compensated crystal oscillators (TCXO) or oven-controlled crystal oscillators (OCXO) may be used. TCXOs try to adjust their oscillation frequency electronically, to compensate for temperature changes. OCXOs, on the other hand, try to maintain a constant temperature with a mini-oven around the crystal. For very sensitive applications, atomic clocks may be used for even lower drift. But given long enough time, even the most precise of these oscillators will accumulate tiny errors and the clocks will eventually drift!
****

A few more read-only per-link parameters provide synchronization information about the link, when available:

* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#sync[`sync`^] -- availability of synchronization information on link
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#lastSync[`lastSync`^] -- time of last synchronization (epoch milliseconds)
* {url-unet-javadoc}org/arl/unet/localization/RangingParam.html#offset[`offset`^] -- clock offset between current node and peer node (microseconds)

=== Examples

In order to understand how the RANGING service provides OWTT and TWTT ranging, it is instructive to try a few examples using the Netiquette 3-node network simulation (`bin/unet samples/netq-network.groovy`). Start the simulation, and connect to node A:

[source]
----
> agentsForService(org.arl.unet.Services.RANGING)  //<1>
[ranging]
> ranging
« Range estimator »

Provides time synchronization and range estimation services.

[org.arl.unet.localization.RangingParam]
  channel = 2                                      //<2>
  ipreamble = 0
  mac = mac
  maxRange = 3000.0
  phy = phy
  rdelay = 1.95
  respond = true
  rpreamble = 0
  rsignal = []
  threshold = 0.3

> range host('B')                                  //<3>
371.09
> ranging << new RangeReq(to: host('B'))           //<4>
AGREE
ranging >> RangeNtf:INFORM[from:232 to:31 range:371.08856 offset:-1523892589 rxTime:1860655032]
> ntf.range
371.09
----
<1> We see that the `ranging` agent provides the RANGING service on the node.
<2> The DATA channel (channel 2) is being used for ranging.
<3> The `range` command provides us the range to node B of about 371 m.
<4> The `range` command is implemented by sending a `RangeReq` to the `ranging` agent. We directly send that message. As expected, it leads to a `RangeNtf` message that gives us the same range estimate as the `range` command. The `RangeNtf` also provides us time synchronization information between the nodes (as time difference between the nodes, or `offset`, in microseconds).

==== Two-way travel time ranging

The range measurement above used TWTT ranging. While node B participated in the range measurement by responding to node A's request for a two-way frame exchange, this is all done quietly and we see nothing on node B's shell. To see what is happening on both nodes, subscribe to the `phy` and `ranging` agent's topics on both nodes. Then repeat the `RangeReq` on node A:

.Node A:
[source]
----
> subscribe phy
> subscribe ranging
> ranging << new RangeReq(to: host('B'))
AGREE
phy >> TxFrameStartNtf:INFORM[type:DATA txTime:2048652195 txDuration:700]
phy >> RxFrameStartNtf:INFORM[type:DATA rxTime:2051086032]
phy >> RxFrameNtf:INFORM[type:DATA from:31 to:232 protocol:1 rxTime:2051086032 txTime:526951606 (7 bytes)]
ranging >> RangeNtf:INFORM[from:232 to:31 range:371.08856 offset:-1523892589 rxTime:2051086032]
----

We see that node A transmitted a DATA frame. It then received a timestamped DATA frame back from node B. The timing information in both frames was used to compute the range and time offset between the nodes. This was sent back to us as a `RangeNtf`. This is the frame exchange that implements TWTT ranging.

If we look at node B's shell at the same time:

.Node B:
[source]
----
> subscribe phy
> subscribe ranging
phy >> RxFrameStartNtf:INFORM[type:DATA rxTime:525001443]
phy >> RxFrameNtf:INFORM[type:DATA from:232 to:31 protocol:1 rxTime:525001443 (1 byte)]
ranging >> InterrogationNtf:INFORM[type:DATA from:232 to:31 rxTime:525001443 responded:true]
phy >> TxFrameStartNtf:INFORM[type:DATA txTime:526951606 txDuration:700]
----

We see that node B received a DATA frame and responded back with a DATA frame. It generated a `InterrogationNtf` with `responded` set to `true` to indicate that it received an interrogation and responded to it. This is because `ranging.respond = true`, as seen above. If `ranging.respond` was set to `false`, the agent would have simply generated the `InterrogationNtf` without responding. This allows another agent to study the intorrogation, and optionally send back payload data as part of the response, using the `RespondReq` message.

==== Synchronization

We can ask node A for the synchronization information it has gathered from previous ranging exchanges:

.Node A:
[source]
----
> ranging[host('B')]
« RANGING »

[org.arl.unet.localization.RangingNodeParam]
  address ⤇ 31
  channel = 2
  data = []
  ipreamble = 0
  isignal = []
  lastSync ⤇ 1586070856974
  lifetime = 0
  maxRange = 3000.0
  offset = -1523892589
  rdelay = 1.95
  rpreamble = 0
  rsignal = []
  sync ⤇ false
  threshold = 0.3
----

We see that it has stored the time offset to node B, along with the information on when the synchronization information was last updated. However, you'll find that the `sync` flag is `false`, since the `lifetime` parameter was set to 0, and hence the synchronization is considered expired. If you ask for synchronization information on node B, you'll find that it does not have any:

.Node B:
[source]
----
> ranging[host('A')]
« RANGING »

[org.arl.unet.localization.RangingNodeParam]
  address ⤇ 232
  channel = 2
  data = []
  ipreamble = 0
  isignal = []
  lastSync ⤇ 0
  lifetime = 0
  maxRange = 3000.0
  offset = 0
  rdelay = 1.95
  rpreamble = 0
  rsignal = []
  sync ⤇ false
  threshold = 0.3
----

Without synchronization information, OWTT ranging cannot be performed.

If we have low-drift clocks on all our nodes, we can set the `lifetime` parameter for all the links to a larger value. Let's do that on node A for link A-B. Also unsubscribe from `phy` to avoid too much clutter:

.Nodes A:
[source]
----
> ranging[host('B')].lifetime = 3600
3600
> unsubscribe phy
----

Now check the synchronization information for link A-B again:

.Node A:
[source]
----
> ranging[host('B')]
« RANGING »

[org.arl.unet.localization.RangingNodeParam]
  address ⤇ 31
  channel = 2
  data = []
  ipreamble = 0
  isignal = []
  lastSync ⤇ 1586070856974
  lifetime = 0
  maxRange = 3000.0
  offset = -1523892589
  rdelay = 1.95
  rpreamble = 0
  rsignal = []
  sync ⤇ true            //<1>
  threshold = 0.3
----
<1> We see that `sync` is now true, indicating that we have valid synchronization information on this link.

==== One-way travel time ranging

Now, let's transmit a ranging beacon from node B:

.Node B
[source]
----
> ranging << new BeaconReq()
AGREE
----

On node A, we see `RangeNtf` from the OWTT ranging:

.Node A
[source]
----
ranging >> RangeNtf:INFORM[from:232 to:31 range:371.08856 rxTime:1039174911]
----

TIP: Any timestamped frame transmission from node B will generate `RangeNtf` on node A now. This can be used to piggyback data (e.g. 42) along with the beacon: `phy << new TxFrameReq(timestamped: true, data: [42])`. This will generate a `RxFrameNtf`
on node A, if you subscribe to `phy`, in addition to the `RangeNtf` messages. This works with both CONTROL and DATA frames.

==== Ranging to COTS transponders

The ranging agent provides a lot of flexibility for configuration. To see the power of this, let's consider a scenario in which we want to use a UnetStack-based modem to measure range to a COTS transponder that is configured to respond to a 22 kHz 2 ms long pulse with a 30 kHz 2 ms pulse, after a delay of 30 ms.

First, we welcome the COTS transponder into our network as a Unet _guest_ node by assigning it a name and address. Let's call it node T with address `host('T') = 152`. On our modem node, we set up details of the link to the transponder:

[source]
----
> T = host('T')
152
> ranging[T].isignal = cw(22.kHz, 2.ms);
> ranging[T].rsignal = cw(30.kHz, 2.ms);
> ranging[T].rdelay = 30.ms;
> ranging
« RANGING »

[org.arl.unet.localization.RangingNodeParam]
  address ⤇ 152
  channel = 2
  data = []
  ipreamble = 0
  isignal = [0.0, -0.0, 0.8660254, -0.5, 0.5 ... 0.5, 0.8660254, 0.8660254, 0.5]
  lastSync ⤇ 0
  lifetime = 0
  maxRange = 3000.0
  offset = 0
  rdelay = 0.03
  rpreamble = 0
  rsignal = [0.0, 0.0, 6.123234E-17, 1.0, -1 ... 6022E-15, -3.1847007E-15, -1.0]
  sync ⤇ false
  threshold = 0.3
----

Now, we are all setup. To range to the transponder, all we need to do is:

[source]
----
> range T
235.7
----

Assuming you have the UnetStack-based modem in the water, along with the COTS transponder, you'll get a range estimate back after just a short delay.

TIP: If you don't have a UnetStack-based modem, you can still try out the above example on Unet audio, and hear the interrogation pulse. However, because the default operating band of Unet audio SDOAM is 6-18 kHz, you'll need to pick interrogation and response frequencies in this band. Also, you may want to make the interrogation pulse longer (say 200 ms), so you can hear it when you try ranging with this in air.

We have hardly scratched the surface of what the RANGING service and the ranging agent is capable of. For example, with multiple nodes connected over wormholes (<<Wormholes>>) and ranging to a mobile node, you can easily deploy a simple long-baseline (LBL) navigation system!
