== UnetSocket API

The command shell is great for manual configuration and interaction, but often we require programmatic interaction from an external application. For this, we have the UnetSocket API (available in Java, Groovy, Python, Julia and C). While the exact syntax differs across languages, the basic concepts remain the same. We focus on the use of the API in Groovy in this section, but also show some examples in other languages.

External applications interact with UnetStack via a UnetSocket API using fjåge's connector framework. This allows the API to access UnetStack over a TCP/IP connection, a serial port, or any other fjåge connector that may be available. To open a TCP/IP connection to UnetStack, we need to know the IP address and port of the API connector on UnetStack. Simply type `iface` on a shell to find this information.

NOTE: The examples in this chapter assume that you are running `bin/unet samples/2-node-network.groovy` and connected to a web shell for node A.

[source, console]
----
> iface
tcp://192.168.1.9:1101 [API]
ws://192.168.1.9:8081/ws [API]
websh: ws://192.168.1.9:8081/fjage/shell/ws [GroovyScriptEngine]
----

The first entry starting with `tcp://` is the API connector available over TCP/IP. The IP address and port number in this case are `192.168.1.9` and `1102` respectively. The IP address on your setup might differ, so remember to replace it in the example code below when you try it.

=== Connecting to UnetStack

To connect to UnetStack from Groovy, typical code might look something like this:

[source, groovy]
----
import org.arl.unet.api.UnetSocket

def sock = new UnetSocket('192.168.1.9', 1102)
// do things with sock here
sock.close()
----

TIP: The UnetSocket API can also be used directly from the shell. To do this, we create a socket connected to the local node with `sock = new UnetSocket(this)`. Here `this` refers to the local UnetStack instance. Do note that the `def` is typically not used in the shell, as we usually want the `sock` variable to be created in the shell's context. However, we use `def` in Groovy scripts or closures to keep the `sock` variable in the local context.

and in Python:

[source, python]
----
from unetpy import UnetSocket

sock = UnetSocket('192.168.1.9', 1102)
# do things with sock here
sock.close()
----

=== Sending data

To send datagrams using a socket, we first specify the destination address and protocol number using the `connect()` method, and then use the `send()` method to send data (byte array). In Groovy:

[source, groovy]
----
def to = sock.host('B')              #<1>
sock.connect(to, 0)                  #<2>
sock.send('hello!' as byte[])        #<3>
sock.send('more data!' as byte[])
----
<1> Resolve node name to address. If the destination address is already known, this step can be skipped.
<2> Connect using protcol 0 (generic data). Constant `org.arl.unet.Protocol.DATA` may be used instead of 0 for improved readability.
<3> Data has to be converted into a `byte[]` for transmission using the `send()` method.

If only a single `send()` is desired, the `connect()` call may be omitted and the destination and protocol number can be provided as parameters to `send()`:

[source, groovy]
----
sock.send('hello!' as byte[], to, 0)
----

=== Receiving data

On the receiving end, we specify the protocol number to listen to using `bind()`, and then receive a datagram using the `receive()` method:

[source, groovy]
----
sock.bind(0)
def rx = sock.receive()
println(rx.from, rx.to, rx.data)
----

TIP: Unbound sockets listen to all unreserved protocols. So the `bind()` call above could be skipped, if we would like to listen to all application datagrams.

The `receive()` method above is blocking by default. The blocking behavior can be controlled using the `setTimeout()` method, where the blocking timeout can be specified in milliseconds. A timeout of 0 makes the call non-blocking. If no message is available at timeout, a `null` value is returned. When the `receive()` call is blocked, a call to `cancel()` can unblock and cause the `receive()` call to return immediately.

=== Getting & setting parameters

As we have seen before, agent parameters provide Unet information that an application may require. Applications may also need to change parameters to control the behavior of the agents in UnetStack. To access agent parameters, we first have to look up the relevant agent based on its name or a service that it provides. For example:

[source, groovy]
----
def phy = sock.agentForService(org.arl.unet.Services.PHYSICAL)
println(phy.MTU)
println(phy[1].dataRate)
----

will print the value of parameter `MTU` (maximum transfer unit) of the physical layer, and the physical layer `dataRate` of the CONTROL (1) channel. We could also change some of the parameters:

[source, groovy]
----
println(phy[2].frameLength)
phy[1].frameLength = 64
println(phy[2].frameLength)
println(phy.MTU)
----

If you run the above code, you'll see that the changed DATA (2) channel frame length would also affect the MTU. The `phy.MTU`, `phy[1].MTU`, `phy[2].MTU`, `phy[1].frameLength` and `phy[2].frameLength` parameters are closely related. The MTU of a channel is its frame length, reduced by the size of the physical layer header. The MTU of the physical layer is the MTU of the DATA channel, since a datagram is by default transmitted using the DATA channel.

TIP: Developers may wish to consider using constants `org.arl.unet.phy.Physical.CONTROL` and `org.arl.unet.phy.Physical.DATA` instead of hard coding 1 and 2, for readability.

=== Accessing agent services

As we have already seen in <<Interacting with agents using messages>>, the full functionality of UnetStack can be harnessed by sending/receiving messages to/from various agents in the stack. We earlier saw how to do that from the shell. We now look at how to use the UnetSocket API to send/receive messages to/from agents.

To request broadcast of a CONTROL frame, like we did from the shell before, we need to lookup the agent providing the PHYSICAL service and send a `TxFrameReq` to it:

[source, groovy]
----
def phy = sock.agentForService(org.arl.unet.Services.PHYSICAL)
phy << new org.arl.unet.phy.TxFrameReq()
----

For lower level transactions, we obtain a fjåge Gateway instance from the UnetSocket API, and use it directly. For example, we can subscribe to event notifications from the physical layer and print them:

[source, groovy]
----
def gw = sock.gateway
gw.subscribe(phy)
def msg = gw.receive(10000)     #<1>
if (msg) println(msg)
gw.unsubscribe(phy)
----
<1> Receive a message from the gateway without a timeout of 10000 ms. If no message is received during this period, `null` is returned.
