title: Unet
longname: UnetStack
description: The Underwater Networks Project. Design, simulate, test and deploy underwater acoustic networks with an agent-based network stack and simulator.
url: "https://unetstack.net"
website: "https://unetstack.net"
markdown: kramdown
theme: minima
twitter: unetstack
image_path: img/logo.png
sass:
  style: compressed
  sourcemap: false
github:
  repository_url: https://github.com/org-arl/unet-doc
